# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: ssh tunnel to mysql database
      run: |
        mkdir -p ~/.ssh/
        ssh-keyscan -H ara.uberspace.de >> ~/.ssh/known_hosts
        eval `ssh-agent -s`
        ssh-add - <<< "${{secrets.SSH_PRIVATE_KEY}}"
        ssh -fN -L 3306:127.0.0.1:3306 duostori@ara.uberspace.de

    - name: Install
      run: cd next && npm install

    - run: printf "${{ secrets.ENV_LOCAL }}" >> next/.env.local

    - name: Build
      run: cd next && npm run build

    - name: zip
      run: zip -r build.zip next/.next

    - name: upload
      run: |
        ssh-keyscan -H ara.uberspace.de >> ~/.ssh/known_hosts
        eval `ssh-agent -s`
        ssh-add - <<< "${{secrets.SSH_PRIVATE_KEY}}"
        ssh duostori@ara.uberspace.de 'cd html && ./create_deployment.py ${{ github.ref }}'       
        scp build.zip duostori@ara.uberspace.de:~/html/deploy_${{ github.ref }}/
        ssh duostori@ara.uberspace.de 'rm -rf ~/html/deploy_${{ github.ref }}/next/.next'
        ssh duostori@ara.uberspace.de 'unzip -d ~/html/deploy_${{ github.ref }}/ ~/html/deploy_${{ github.ref }}/build.zip'
        ssh duostori@ara.uberspace.de 'supervisorctl restart deploy_${{ github.ref }}'
